# Generated by Django 4.2.1 on 2023-05-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_name", models.TextField()),
                ("arrives", models.TimeField()),
                ("departs", models.TextField()),
                ("stop_time", models.TextField()),
                ("mon", models.TextField()),
                ("tue", models.TextField()),
                ("wed", models.TextField()),
                ("thu", models.TextField()),
                ("fri", models.TextField()),
                ("sat", models.TextField()),
                ("sun", models.TextField()),
            ],
        ),
    ]
